/**
 * components/Reviews/AssumedTimesSection.tsx — Settle the period's assumed times
 *
 * The review is where autogenerated data gets its audit. Every completion the app
 * timed on the user's behalf — a habit's duration from its per-unit rate, a finish
 * time assumed to be "just now" or the day anchor — is flagged
 * (`lib/estimated-values.ts`) and collected here for the period being reviewed.
 *
 * Two paths out, deliberately: fix the handful that are wrong, then accept the rest
 * in one click. Confirming is what stops the habit sync from re-deriving over the
 * numbers, so the point of this step is to convert cheap guesses into settled record.
 */
"use client"

import { useMemo, useState } from "react"
import { format } from "date-fns"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Check, Wand2 } from "lucide-react"
import type { ReviewPeriod, Task } from "@/lib/types"
import { useTaskStore } from "@/lib/task-store"
import {
  describeEstimates,
  formatDurationMinutes,
  hasUnconfirmedEstimates,
  unconfirmedEstimates,
  estimatedFieldLabel,
} from "@/lib/estimated-values"
import { confirmAllTaskTimes, confirmTaskTimes } from "@/lib/services/completion-time-service"
import {
  taskCompletedInMonth,
  taskCompletedInWeek,
  taskCompletedOnDay,
} from "@/components/Home/ToDo/todo-utils"
import { dateFromPeriodKey } from "@/lib/reviews-store"
import { itemTitle } from "@/lib/item-utils"

function completedInPeriod(task: Task, period: ReviewPeriod, key: string): boolean {
  const ref = dateFromPeriodKey(period, key)
  switch (period) {
    case "day":
      return taskCompletedOnDay(task, ref)
    case "week":
      return taskCompletedInWeek(task, key)
    case "month":
      return taskCompletedInMonth(task, key)
    default:
      // Quarter/year reviews are too coarse for minute-level confirmation.
      return false
  }
}

function AssumedTimeRow({ task, period }: { task: Task; period: ReviewPeriod }) {
  const completedAt = task.completedDate
  const [time, setTime] = useState(() => (completedAt ? format(completedAt, "HH:mm") : ""))
  const [minutes, setMinutes] = useState(() => String(task.actualDuration ?? ""))

  const save = () => {
    if (!completedAt) return
    const [hours, mins] = time.split(":").map((part) => Number.parseInt(part, 10))
    const corrected = new Date(completedAt)
    if (Number.isFinite(hours) && Number.isFinite(mins)) corrected.setHours(hours, mins, 0, 0)
    const parsed = Number.parseFloat(minutes)
    confirmTaskTimes(task.id, {
      completedAt: corrected,
      durationMinutes: minutes.trim() === "" ? 0 : Number.isFinite(parsed) ? parsed : undefined,
    })
  }

  const pending = unconfirmedEstimates(task.estimates)

  return (
    <div className="border rounded-md p-2 space-y-2">
      <div className="flex items-start justify-between gap-2">
        <div className="min-w-0">
          <p className="text-sm truncate">{itemTitle(task)}</p>
          <p className="text-xs text-muted-foreground">
            {period !== "day" && completedAt && `${format(completedAt, "MMM d")} · `}
            assumed {pending.map((e) => estimatedFieldLabel(e.field)).join(", ")}
            {task.actualDuration !== undefined && ` · ~${formatDurationMinutes(task.actualDuration)}`}
          </p>
        </div>
        <Button
          size="sm"
          variant="outline"
          className="h-7 shrink-0"
          title={describeEstimates(task.estimates)}
          onClick={() => confirmTaskTimes(task.id)}
        >
          <Check className="h-3.5 w-3.5 mr-1" />
          Looks right
        </Button>
      </div>

      <p className="text-xs text-muted-foreground">{pending[0]?.basis}</p>

      <div className="flex flex-wrap items-center gap-2">
        <label className="text-xs text-muted-foreground">
          Finished
          <input
            type="time"
            value={time}
            onChange={(e) => setTime(e.target.value)}
            className="ml-1.5 h-7 rounded-md border bg-background px-1.5 text-xs"
          />
        </label>
        <label className="text-xs text-muted-foreground">
          Took
          <input
            type="number"
            min="0"
            step="5"
            value={minutes}
            onChange={(e) => setMinutes(e.target.value)}
            placeholder="min"
            className="ml-1.5 h-7 w-16 rounded-md border bg-background px-1.5 text-xs"
          />
          <span className="ml-1">min</span>
        </label>
        <Button size="sm" variant="outline" className="h-7" onClick={save}>
          Save correction
        </Button>
      </div>
    </div>
  )
}

export function AssumedTimesSection({ period, periodKey }: { period: ReviewPeriod; periodKey: string }) {
  const tasks = useTaskStore((s) => s.tasks)

  const pending = useMemo(
    () =>
      tasks
        .filter((task) => task.completed && hasUnconfirmedEstimates(task) && completedInPeriod(task, period, periodKey))
        .sort((a, b) => (a.completedDate?.getTime() ?? 0) - (b.completedDate?.getTime() ?? 0)),
    [tasks, period, periodKey],
  )

  if (period === "quarter" || period === "year") return null

  return (
    <section className="space-y-2">
      <div className="flex items-center justify-between gap-2">
        <Label className="font-semibold text-sm flex items-center gap-2">
          <Wand2 className="h-4 w-4" />
          Assumed times ({pending.length})
        </Label>
        {pending.length > 0 && (
          <Button
            size="sm"
            variant="outline"
            className="h-7"
            onClick={() => confirmAllTaskTimes(pending.map((t) => t.id))}
          >
            <Check className="h-3.5 w-3.5 mr-1" />
            Confirm all as-is
          </Button>
        )}
      </div>

      {pending.length === 0 ? (
        <p className="text-sm text-muted-foreground">
          Nothing to settle — every completed item this {period} has a time you confirmed or the app observed.
        </p>
      ) : (
        <>
          <p className="text-sm text-muted-foreground">
            These times were filled in for you from habit rates and tracked time. Correct the ones that are off and
            confirm the rest — confirmed values stop being re-derived.
          </p>
          <div className="space-y-2">
            {pending.map((task) => (
              <AssumedTimeRow key={task.id} task={task} period={period} />
            ))}
          </div>
        </>
      )}
    </section>
  )
}
