/**
 * lib/services/completion-time-service.ts — Confirm or correct an autogenerated time
 *
 * The other side of the estimate contract (`lib/estimated-values.ts`): the app
 * derives when a completion happened and how long it took, and the user settles it
 * here — from the **est.** chip in Home → To Do → Done, or in bulk from the review
 * dialog's "Assumed times" section.
 *
 * Confirming is not the same as accepting a number: a corrected value is stamped
 * confirmed too, which is what stops the habit sync from re-deriving over it.
 * The start time follows the finish and duration unless it is given explicitly, so
 * a caller only has to supply the numbers the user actually touched.
 */
import type { EstimatedField, Task } from "@/lib/types"
import { taskRepository } from "@/lib/data/task-repository"
import { clearEstimates, confirmEstimates } from "@/lib/estimated-values"

export interface ConfirmedTimes {
  /** Corrected finish time. Omit to keep what was derived. */
  completedAt?: Date
  /** Corrected start. Omit to re-derive it from the finish and the duration. */
  startedAt?: Date
  /** Corrected length in minutes. `0` clears the duration and drops its flag. */
  durationMinutes?: number
}

const MS_PER_MINUTE = 60_000

/**
 * Apply `values` to `task` and mark every field it covers as confirmed. Fields the
 * user left alone keep their derived value but are confirmed too — "yes, that's
 * right" is an answer, and it has to stick.
 */
export function applyConfirmedTimes(task: Task, values: ConfirmedTimes = {}): Task {
  const completedDate = values.completedAt ?? task.completedDate
  const clearsDuration = values.durationMinutes === 0
  const duration = clearsDuration
    ? undefined
    : values.durationMinutes !== undefined
      ? Math.max(0, Math.round(values.durationMinutes))
      : task.actualDuration

  const startedAt =
    values.startedAt ??
    (completedDate && duration !== undefined
      ? new Date(completedDate.getTime() - duration * MS_PER_MINUTE)
      : task.startedAt)

  const confirmedFields: EstimatedField[] = ["completedDate", "startedAt", "actualDuration"]
  const estimates = clearsDuration
    ? clearEstimates(confirmEstimates(task.estimates, confirmedFields), ["actualDuration"])
    : confirmEstimates(task.estimates, confirmedFields)

  return {
    ...task,
    completedDate,
    startedAt,
    actualDuration: duration,
    // Keep the plan number aligned while it is only ever a mirror of the estimate.
    estimatedDuration: duration ?? task.estimatedDuration,
    estimates: estimates?.length ? estimates : undefined,
  }
}

/** Persist a confirmation/correction for one Done row. */
export function confirmTaskTimes(taskId: string, values: ConfirmedTimes = {}): Task | undefined {
  const task = taskRepository.getById(taskId)
  if (!task) return undefined
  return taskRepository.update(applyConfirmedTimes(task, values))
}

/** Accept every assumed time on these rows as-is (the review's "looks right" path). */
export function confirmAllTaskTimes(taskIds: string[]): number {
  let confirmed = 0
  for (const id of taskIds) {
    if (confirmTaskTimes(id)) confirmed += 1
  }
  return confirmed
}
