/**
 * lib/completion-window.ts — Where in the day a completion actually sat
 *
 * Autogenerated Done rows used to be stamped at noon local, every time, for every
 * day. That is a placeholder masquerading as data: it buckets into the right day
 * and tells you nothing else. This derives a real window instead — a start and a
 * finish — from the best evidence available, and says which halves of it were
 * assumed so `lib/estimated-values.ts` can flag them.
 *
 * Evidence, best first:
 *   1. **Painted Tracking time.** The finish time is read off the last minute the
 *      user painted on the habit's tags, so it is observed. The start walks back
 *      through the contiguous run; only if the run is shorter than the duration
 *      does the start become an assumption.
 *   2. **The day is still running.** Assume the work finished just now and started
 *      a duration ago — ticking a habit off normally happens right after doing it.
 *   3. **The day is over.** Fall back to half an hour before that night's bedtime
 *      — stated, painted on the grid, or the user's own median over the last
 *      month (`lib/sleep-sync.ts` picks which). Only with no sleep evidence at
 *      all does this reach the fixed day anchor (default 9:00 PM,
 *      `lib/user-settings-store.ts`).
 *
 * Whichever branch runs, the window is **clamped to the user's waking hours**: a
 * session is never backdated into minutes the sleep log says they were asleep.
 * With no logged night the floor is local midnight, exactly as before.
 *
 * Pure: takes `now`, the painted minutes, the anchor and the night as arguments.
 */
import { format } from "date-fns"
import { MINUTES_PER_DAY } from "@/lib/time-entries"
import type { EstimatedField, EstimateKind } from "@/lib/types"

/** Late enough to be plausible for most habits, early enough to precede sleep. */
export const DEFAULT_DAY_ANCHOR_MINUTES = 21 * 60 // 9:00 PM

export interface CompletionWindow {
  startedAt: Date
  completedAt: Date
  kind: EstimateKind & ("tracked" | "now" | "anchor")
  /** Which of the two ends were assumed rather than observed. */
  estimatedFields: EstimatedField[]
  basis: string
}

const MS_PER_MINUTE = 60_000

function startOfDay(date: Date): Date {
  return new Date(date.getFullYear(), date.getMonth(), date.getDate(), 0, 0, 0, 0)
}

function sameLocalDay(a: Date, b: Date): boolean {
  return (
    a.getFullYear() === b.getFullYear() && a.getMonth() === b.getMonth() && a.getDate() === b.getDate()
  )
}

export function clampAnchorMinutes(minutes: number | undefined): number {
  if (!Number.isFinite(minutes)) return DEFAULT_DAY_ANCHOR_MINUTES
  return Math.min(MINUTES_PER_DAY - 1, Math.max(0, Math.round(minutes as number)))
}

/** "9:00 PM" for a minutes-past-midnight anchor. */
export function formatAnchorMinutes(minutes: number): string {
  const clamped = clampAnchorMinutes(minutes)
  const base = new Date(2000, 0, 1, 0, 0, 0, 0)
  return format(new Date(base.getTime() + clamped * MS_PER_MINUTE), "h:mm a")
}

/**
 * The run of painted minutes ending at the last painted minute of the day, as
 * `[firstMinute, lastMinute]`. Scattered paint (morning and evening) yields only
 * the evening run, which is the one the completion closed.
 */
export function lastPaintedRun(minutes: Iterable<number>): [number, number] | null {
  const sorted = [...new Set([...minutes])].filter((s) => Number.isInteger(s) && s >= 0).sort((a, b) => a - b)
  if (sorted.length === 0) return null
  const last = sorted[sorted.length - 1]
  let first = last
  for (let i = sorted.length - 2; i >= 0; i--) {
    if (sorted[i] === first - 1) first = sorted[i]
    else break
  }
  return [first, last]
}

export interface CompletionWindowInput {
  /** The calendar day the completion belongs to. */
  date: Date
  /** Minutes the work took, when known. 0/undefined gives a zero-length window. */
  durationMinutes?: number
  /** Minutes past midnight painted on the habit's tags (`lib/tracked-time.ts`). */
  trackedMinutes?: Iterable<number>
  now?: Date
  /** Minutes past midnight to assume for a day that is already over. */
  anchorMinutes?: number
  /**
   * The day's waking hours from the sleep log (`lib/sleep-log.ts`), when known.
   * `wake` is the minute the user got up; `bed` is the minute they fell asleep
   * that night, which may be ≥ 1440 for an after-midnight bedtime. `source` says
   * how firmly `bed` is known, so the basis line can be honest about it.
   */
  awake?: { wake?: number; bed?: number; source?: SleepEvidence }
}

/** Where a sleep time came from — stated, painted, or the user's usual routine. */
export type SleepEvidence = "logged" | "tracked" | "typical"

const SLEEP_BASIS: Record<SleepEvidence, string> = {
  logged: "the last of your waking hours that day, per your sleep log",
  tracked: "the last of your waking hours that day, per the sleep you painted in Tracking",
  typical: "the last of your waking hours that day, going by the time you usually go to bed",
}

export function completionWindow({
  date,
  durationMinutes = 0,
  trackedMinutes,
  now = new Date(),
  anchorMinutes,
  awake,
}: CompletionWindowInput): CompletionWindow {
  const dayStart = startOfDay(date)
  const duration = Math.max(0, Math.round(durationMinutes))

  // A logged night beats a fixed anchor: the last hour before bed is a better
  // guess for "when did this happen" than a 9 PM default that may be two hours
  // after the user was actually asleep.
  const bedAnchor = awake?.bed !== undefined ? Math.min(MINUTES_PER_DAY - 1, Math.max(0, awake.bed - 30)) : undefined
  const anchor = bedAnchor ?? clampAnchorMinutes(anchorMinutes)
  const anchorFromSleep = bedAnchor !== undefined

  const atMinute = (minutes: number) => new Date(dayStart.getTime() + minutes * MS_PER_MINUTE)
  // The day's floor is when the user got up, not midnight — backdating a session
  // into hours they were demonstrably asleep is worse than a shorter window.
  const wakeFloor = dayStart.getTime() + Math.max(0, Math.min(MINUTES_PER_DAY - 1, awake?.wake ?? 0)) * MS_PER_MINUTE
  const back = (from: Date) => {
    // Only clamp when the finish is itself after waking. Something recorded at
    // 3am on a day you got up at 7 is unusual but real, and squashing it forward
    // would invent a time rather than decline to guess one.
    const floor = from.getTime() >= wakeFloor ? wakeFloor : dayStart.getTime()
    return new Date(Math.max(floor, from.getTime() - duration * MS_PER_MINUTE))
  }

  const run = trackedMinutes ? lastPaintedRun(trackedMinutes) : null
  if (run) {
    const [firstMinute, lastMinute] = run
    const completedAt = atMinute(lastMinute + 1)
    const runStart = atMinute(firstMinute)
    const runMinutes = lastMinute - firstMinute + 1
    // A run at least as long as the duration contains the whole session, so both
    // ends are observed. A shorter run means part of the work went unpainted.
    const covered = runMinutes >= duration
    const startedAt = covered ? runStart : back(completedAt)
    return {
      startedAt,
      completedAt,
      kind: "tracked",
      estimatedFields: covered ? [] : ["startedAt"],
      basis: covered
        ? `painted in Tracking ${format(startedAt, "h:mm a")}–${format(completedAt, "h:mm a")}`
        : `finished ${format(completedAt, "h:mm a")} per painted Tracking time, start assumed from the duration`,
    }
  }

  if (sameLocalDay(date, now)) {
    return {
      startedAt: back(now),
      completedAt: now,
      kind: "now",
      estimatedFields: duration > 0 ? ["completedDate", "startedAt"] : ["completedDate"],
      basis: `assumed finished just now (${format(now, "h:mm a")})`,
    }
  }

  const completedAt = atMinute(anchor)
  return {
    startedAt: back(completedAt),
    completedAt,
    kind: "anchor",
    estimatedFields: duration > 0 ? ["completedDate", "startedAt"] : ["completedDate"],
    basis: anchorFromSleep
      ? `assumed around ${format(completedAt, "h:mm a")} — ${SLEEP_BASIS[awake?.source ?? "logged"]}`
      : `assumed around ${format(completedAt, "h:mm a")} — that day was already over`,
  }
}
