/**
 * lib/estimated-values.ts — Provenance for autogenerated values
 *
 * The app fills in time data on the user's behalf: how long a habit took (from
 * its per-unit rate), and where in the day the work sat (from painted Tracking
 * slots, or from "you just ticked it off"). None of that is passed off as
 * observed fact. Every derived value leaves a `FieldEstimate` on the record
 * naming the field, how it was produced, and the sentence explaining it, so the
 * Done list can mark it and the review can ask the user to confirm or correct it.
 *
 * Confirmation is sticky: once a field is confirmed, re-running the derivation
 * must not overwrite the user's number (`canRegenerate`). That is what makes
 * autogeneration safe to run on every habit edit.
 *
 * Pure: no store imports, so both the habit sync and the UI can use it.
 */
import type { EstimatedField, EstimateKind, FieldEstimate, Task } from "@/lib/types"
import { itemTitle } from "@/lib/item-utils"
import { formatDuration } from "@/lib/time-entries"

/** Every field an estimate may cover, in the order the review presents them. */
export const ESTIMATED_FIELDS: EstimatedField[] = ["completedDate", "startedAt", "actualDuration"]

const FIELD_LABELS: Record<EstimatedField, string> = {
  completedDate: "finish time",
  startedAt: "start time",
  actualDuration: "duration",
}

export function estimatedFieldLabel(field: EstimatedField): string {
  return FIELD_LABELS[field] ?? field
}

export function makeEstimate(
  field: EstimatedField,
  kind: EstimateKind,
  basis: string,
  generatedAt: Date = new Date(),
): FieldEstimate {
  return { field, kind, basis, generatedAt: generatedAt.toISOString() }
}

export function findEstimate(
  estimates: FieldEstimate[] | undefined,
  field: EstimatedField,
): FieldEstimate | undefined {
  return estimates?.find((e) => e.field === field)
}

/** True while the value is still assumed — present, and not yet confirmed. */
export function isEstimated(estimates: FieldEstimate[] | undefined, field: EstimatedField): boolean {
  const found = findEstimate(estimates, field)
  return !!found && !found.confirmedAt
}

export function isConfirmed(estimates: FieldEstimate[] | undefined, field: EstimatedField): boolean {
  return !!findEstimate(estimates, field)?.confirmedAt
}

export function unconfirmedEstimates(estimates: FieldEstimate[] | undefined): FieldEstimate[] {
  return (estimates ?? []).filter((e) => !e.confirmedAt)
}

export function hasUnconfirmedEstimates(task: Pick<Task, "estimates">): boolean {
  return unconfirmedEstimates(task.estimates).length > 0
}

/**
 * Whether the derivation is still allowed to write `field`. A confirmed value is
 * the user's, so later syncs leave it alone even when the habit's numbers change.
 */
export function canRegenerate(estimates: FieldEstimate[] | undefined, field: EstimatedField): boolean {
  return !isConfirmed(estimates, field)
}

/**
 * Replace the estimates for the fields `incoming` covers, keeping every other
 * entry (including confirmed ones for untouched fields) as it was.
 */
export function mergeEstimates(
  existing: FieldEstimate[] | undefined,
  incoming: FieldEstimate[],
): FieldEstimate[] {
  const replaced = new Set(incoming.map((e) => e.field))
  return [...(existing ?? []).filter((e) => !replaced.has(e.field)), ...incoming]
}

/** Stamp `fields` (default: everything unconfirmed) as confirmed by the user. */
export function confirmEstimates(
  estimates: FieldEstimate[] | undefined,
  fields?: EstimatedField[],
  at: Date = new Date(),
): FieldEstimate[] {
  const wanted = fields ? new Set(fields) : null
  return (estimates ?? []).map((e) =>
    (!wanted || wanted.has(e.field)) && !e.confirmedAt ? { ...e, confirmedAt: at.toISOString() } : e,
  )
}

/** Drop the flags for `fields` entirely — used when a value is cleared, not corrected. */
export function clearEstimates(
  estimates: FieldEstimate[] | undefined,
  fields: EstimatedField[],
): FieldEstimate[] | undefined {
  const drop = new Set(fields)
  const kept = (estimates ?? []).filter((e) => !drop.has(e.field))
  return kept.length ? kept : undefined
}

/** Tasks in `tasks` still carrying an unconfirmed estimate, oldest completion first. */
export function tasksAwaitingConfirmation(tasks: Task[]): Task[] {
  return tasks
    .filter(hasUnconfirmedEstimates)
    .sort((a, b) => (a.completedDate?.getTime() ?? 0) - (b.completedDate?.getTime() ?? 0))
}

/**
 * One sentence covering everything still assumed on a record, for the badge
 * tooltip. Bases repeat across fields (the window and the duration usually share
 * one), so identical sentences collapse.
 */
export function describeEstimates(estimates: FieldEstimate[] | undefined): string {
  const pending = unconfirmedEstimates(estimates)
  if (pending.length === 0) return ""
  const seen = new Set<string>()
  const lines: string[] = []
  for (const e of pending) {
    if (seen.has(e.basis)) continue
    seen.add(e.basis)
    lines.push(e.basis)
  }
  const fields = pending.map((e) => estimatedFieldLabel(e.field)).join(", ")
  return `Assumed ${fields} — ${lines.join("; ")}. Confirm or correct it in your review.`
}

/** "40m" / "1h 20m" — the Tracking formatter, so durations read the same everywhere. */
export const formatDurationMinutes = formatDuration

/** Need two observed sessions before we will say "usually." */
export const USUAL_DURATION_MIN_SAMPLES = 2

/**
 * Generic kinds are too broad for a type-level usual (every Next Action is
 * `task`). Title match still applies. Named / catalog types (operation, book, …)
 * may fall back to other items of that type.
 */
const GENERIC_USUAL_TYPES = new Set(["", "task", "item", "action", "note"])

export type UsualDurationMatch = "title" | "type"

export interface UsualDuration {
  /** Median of the observed minutes, rounded to a whole minute. */
  minutes: number
  sampleCount: number
  match: UsualDurationMatch
  /** Tooltip / hint sentence — never written onto `Task.estimates`. */
  basis: string
}

export type LikeThisForUsual = Pick<Task, "id"> &
  Partial<Pick<Task, "title" | "description" | "type">>

function titleKey(record: LikeThisForUsual | Task): string {
  return itemTitle(record).replace(/\s+/g, " ").trim().toLowerCase()
}

function typeKey(record: LikeThisForUsual | Task): string {
  return (record.type ?? "").trim().toLowerCase()
}

function medianMinutes(values: number[]): number {
  const sorted = [...values].sort((a, b) => a - b)
  const mid = Math.floor(sorted.length / 2)
  const raw = sorted.length % 2 === 0 ? (sorted[mid - 1] + sorted[mid]) / 2 : sorted[mid]
  return Math.round(raw)
}

/**
 * Observed minutes on one record. `timeLogs` are sessions (preferred, so a
 * rolled-up `actualDuration` is not counted twice). `actualDuration` counts
 * only when it is unflagged — assumed habit rates are not history.
 */
function observedMinutesOn(task: Task, opts: { skipActualDuration: boolean }): number[] {
  const logs = (task.timeLogs ?? [])
    .map((log) => log.durationMinutes)
    .filter((mins) => Number.isFinite(mins) && mins > 0)
  if (logs.length > 0) return logs
  if (opts.skipActualDuration) return []
  const actual = task.actualDuration
  if (actual === undefined || !Number.isFinite(actual) || actual <= 0) return []
  if (isEstimated(task.estimates, "actualDuration")) return []
  return [actual]
}

function usualFrom(samples: number[], match: UsualDurationMatch, likeThis: LikeThisForUsual): UsualDuration | null {
  if (samples.length < USUAL_DURATION_MIN_SAMPLES) return null
  const minutes = medianMinutes(samples)
  if (minutes <= 0) return null
  const noun = match === "title" ? "the same title" : `other ${typeKey(likeThis) || "items"}`
  const sessions = samples.length === 1 ? "session" : "sessions"
  return {
    minutes,
    sampleCount: samples.length,
    match,
    basis: `Median of ${samples.length} observed ${sessions} with ${noun}. Not written onto the estimate field.`,
  }
}

/**
 * Personal "usually takes you N min" from history. Looks at `timeLogs` and
 * unflagged `actualDuration` on items with the same title, then the same
 * (non-generic) item type. Never reads or writes `estimatedDuration`.
 *
 * The probe's own `actualDuration` is skipped (this instance / lifetime total);
 * its past `timeLogs` still count, which is how Working Now learns a repeating
 * operation.
 */
export function usualDurationMinutes(
  tasks: Task[],
  likeThis: LikeThisForUsual | null | undefined,
): UsualDuration | null {
  if (!likeThis) return null
  const title = titleKey(likeThis)
  const kind = typeKey(likeThis)

  const titleSamples: number[] = []
  const typeSamples: number[] = []

  for (const task of tasks) {
    const mins = observedMinutesOn(task, { skipActualDuration: task.id === likeThis.id })
    if (mins.length === 0) continue
    if (title && titleKey(task) === title) titleSamples.push(...mins)
    else if (kind && !GENERIC_USUAL_TYPES.has(kind) && typeKey(task) === kind) typeSamples.push(...mins)
  }

  return usualFrom(titleSamples, "title", likeThis) ?? usualFrom(typeSamples, "type", likeThis)
}

/** Chip copy: "usually ~40m". */
export function formatUsualDuration(usual: UsualDuration): string {
  return `usually ~${formatDurationMinutes(usual.minutes)}`
}
