/**
 * lib/friend-personality-fits.ts — Voice that follows the named photograph
 *
 * Species presets are a starting guess. Named gallery friends get a fit from
 * the cute name plus what is actually in the picture (a “mouse” that is a
 * bat, a “skunk” that is a turtle, a snow marten called a hyrax).
 */

import type { FriendPersonality } from "@/lib/baby-animal-personality"

function fitKey(animalId: string, displayName = ""): string {
  const fromName = displayName
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48)
  return animalId.trim().toLowerCase() || fromName
}

/** Current named friends in the live vault — keyed by `animalId`. */
export const NAMED_FRIEND_PERSONALITY_FITS: Record<string, Partial<FriendPersonality>> = {
  penguin: {
    tone: "direct",
    cadence: "occasional",
    pushiness: "nudge",
    dialogEffect: "stamp",
    whimId: "walk",
    titleLoves: ["order", "walk", "huddle", "chick"],
    habitWeight: 42,
    todoWeight: 28,
    nextActionsWeight: 74,
    loveYouRate: 12,
    whimRate: 10,
    rewardScale: 44,
    suggestionRate: 38,
  },
  fox: {
    tone: "playful",
    cadence: "chatty",
    pushiness: "nudge",
    dialogEffect: "sparkle",
    whimId: "doodle",
    titleLoves: ["plan", "map", "sly"],
    habitWeight: 16,
    todoWeight: 36,
    nextActionsWeight: 86,
    loveYouRate: 14,
    whimRate: 18,
    rewardScale: 42,
    suggestionRate: 48,
  },
  wolf: {
    tone: "coach",
    cadence: "occasional",
    pushiness: "nudge",
    dialogEffect: "stamp",
    whimId: "walk",
    titleLoves: ["pack", "team", "walk"],
    habitWeight: 22,
    todoWeight: 32,
    nextActionsWeight: 84,
    loveYouRate: 10,
    whimRate: 8,
    rewardScale: 48,
    suggestionRate: 40,
  },
  hedgehog: {
    tone: "gentle",
    cadence: "quiet",
    pushiness: "never",
    dialogEffect: "whisper",
    whimId: "curl",
    titleLoves: ["brush", "quiet", "nest"],
    habitWeight: 88,
    todoWeight: 20,
    nextActionsWeight: 22,
    loveYouRate: 8,
    whimRate: 10,
    rewardScale: 36,
    suggestionRate: 22,
  },
  crow: {
    tone: "direct",
    cadence: "occasional",
    pushiness: "nudge",
    dialogEffect: "stamp",
    whimId: "shiny",
    titleLoves: ["file", "write", "shiny", "sort"],
    habitWeight: 14,
    todoWeight: 26,
    nextActionsWeight: 90,
    loveYouRate: 4,
    whimRate: 10,
    rewardScale: 40,
    suggestionRate: 36,
  },
  mouse: {
    tone: "gentle",
    cadence: "quiet",
    pushiness: "never",
    dialogEffect: "whisper",
    whimId: "curl",
    titleLoves: ["night", "rest", "quiet", "dark"],
    habitWeight: 34,
    todoWeight: 18,
    nextActionsWeight: 72,
    loveYouRate: 6,
    whimRate: 12,
    rewardScale: 34,
    suggestionRate: 18,
    urgencyBias: 30,
  },
  axolotl: {
    tone: "playful",
    cadence: "eager",
    pushiness: "celebrate",
    dialogEffect: "sparkle",
    whimId: "doodle",
    titleLoves: ["play", "pink", "costume", "build"],
    habitWeight: 18,
    todoWeight: 78,
    nextActionsWeight: 36,
    loveYouRate: 28,
    whimRate: 22,
    rewardScale: 62,
    suggestionRate: 58,
  },
  "tiny-cute-striped-polecat": {
    tone: "playful",
    cadence: "chatty",
    pushiness: "nudge",
    dialogEffect: "sparkle",
    whimId: "shiny",
    titleLoves: ["hide", "hunt", "brush", "stripe"],
    habitWeight: 18,
    todoWeight: 34,
    nextActionsWeight: 82,
    loveYouRate: 12,
    whimRate: 16,
    rewardScale: 44,
    suggestionRate: 46,
  },
  cub: {
    tone: "playful",
    cadence: "eager",
    pushiness: "celebrate",
    dialogEffect: "bounce",
    whimId: "hop",
    titleLoves: ["play", "tumble"],
    habitWeight: 24,
    todoWeight: 40,
    nextActionsWeight: 72,
    loveYouRate: 20,
    whimRate: 14,
    rewardScale: 50,
    suggestionRate: 52,
  },
  fawn: {
    tone: "gentle",
    cadence: "quiet",
    pushiness: "never",
    dialogEffect: "whisper",
    whimId: "curl",
    titleLoves: ["walk", "quiet", "woods"],
    habitWeight: 42,
    todoWeight: 22,
    nextActionsWeight: 70,
    loveYouRate: 12,
    whimRate: 8,
    rewardScale: 38,
    suggestionRate: 24,
  },
  bunny: {
    tone: "gentle",
    cadence: "quiet",
    pushiness: "never",
    dialogEffect: "whisper",
    whimId: "hop",
    titleLoves: ["garden", "hide", "quiet", "leaf"],
    habitWeight: 70,
    todoWeight: 24,
    nextActionsWeight: 28,
    loveYouRate: 10,
    whimRate: 12,
    rewardScale: 36,
    suggestionRate: 26,
  },
  otter: {
    tone: "playful",
    cadence: "chatty",
    pushiness: "nudge",
    dialogEffect: "bounce",
    whimId: "splash",
    titleLoves: ["play", "water", "splash"],
    habitWeight: 24,
    todoWeight: 82,
    nextActionsWeight: 32,
    loveYouRate: 18,
    whimRate: 22,
    rewardScale: 48,
    suggestionRate: 50,
  },
  seal: {
    tone: "gentle",
    cadence: "occasional",
    pushiness: "nudge",
    dialogEffect: "heart",
    whimId: "splash",
    titleLoves: ["rest", "nap", "water"],
    habitWeight: 28,
    todoWeight: 34,
    nextActionsWeight: 76,
    loveYouRate: 18,
    whimRate: 10,
    rewardScale: 42,
    suggestionRate: 34,
  },
  gosling: {
    tone: "gentle",
    cadence: "occasional",
    pushiness: "nudge",
    dialogEffect: "stamp",
    whimId: "walk",
    titleLoves: ["walk", "follow"],
    habitWeight: 80,
    todoWeight: 30,
    nextActionsWeight: 22,
    loveYouRate: 10,
    whimRate: 10,
    rewardScale: 40,
    suggestionRate: 36,
  },
  puppy: {
    tone: "playful",
    cadence: "eager",
    pushiness: "celebrate",
    dialogEffect: "heart",
    whimId: "walk",
    titleLoves: ["walk", "play", "tiny"],
    habitWeight: 22,
    todoWeight: 90,
    nextActionsWeight: 26,
    loveYouRate: 32,
    whimRate: 12,
    rewardScale: 58,
    suggestionRate: 62,
  },
  goat: {
    tone: "direct",
    cadence: "occasional",
    pushiness: "nudge",
    dialogEffect: "stamp",
    whimId: "stretch",
    titleLoves: ["climb", "jump"],
    habitWeight: 36,
    todoWeight: 74,
    nextActionsWeight: 40,
    loveYouRate: 8,
    whimRate: 14,
    rewardScale: 42,
    suggestionRate: 40,
  },
  skunk: {
    tone: "gentle",
    cadence: "quiet",
    pushiness: "never",
    dialogEffect: "whisper",
    whimId: "soak",
    titleLoves: ["water", "rest", "soak", "swim"],
    habitWeight: 48,
    todoWeight: 22,
    nextActionsWeight: 38,
    loveYouRate: 14,
    whimRate: 16,
    rewardScale: 36,
    suggestionRate: 20,
    urgencyBias: 28,
  },
  owl: {
    tone: "coach",
    cadence: "quiet",
    pushiness: "nudge",
    dialogEffect: "whisper",
    whimId: "read",
    titleLoves: ["read", "book", "study", "tiny"],
    habitWeight: 16,
    todoWeight: 22,
    nextActionsWeight: 90,
    loveYouRate: 8,
    whimRate: 12,
    rewardScale: 46,
    suggestionRate: 28,
  },
  kitten: {
    tone: "playful",
    cadence: "quiet",
    pushiness: "nudge",
    dialogEffect: "sparkle",
    whimId: "doodle",
    titleLoves: ["play", "yarn", "watch", "eye"],
    habitWeight: 18,
    todoWeight: 86,
    nextActionsWeight: 28,
    loveYouRate: 26,
    whimRate: 16,
    rewardScale: 50,
    suggestionRate: 36,
  },
  lamb: {
    tone: "gentle",
    cadence: "occasional",
    pushiness: "celebrate",
    dialogEffect: "heart",
    whimId: "walk",
    titleLoves: ["walk", "garden", "family", "rest"],
    habitWeight: 92,
    todoWeight: 22,
    nextActionsWeight: 16,
    loveYouRate: 18,
    whimRate: 10,
    rewardScale: 46,
    suggestionRate: 34,
  },
  chick: {
    tone: "playful",
    cadence: "chatty",
    pushiness: "nudge",
    dialogEffect: "bounce",
    whimId: "doodle",
    titleLoves: ["play", "peep"],
    habitWeight: 86,
    todoWeight: 26,
    nextActionsWeight: 18,
    loveYouRate: 16,
    whimRate: 16,
    rewardScale: 42,
    suggestionRate: 50,
  },
  duckling: {
    tone: "gentle",
    cadence: "occasional",
    pushiness: "nudge",
    dialogEffect: "whisper",
    whimId: "splash",
    titleLoves: ["bath", "swim", "water"],
    habitWeight: 84,
    todoWeight: 26,
    nextActionsWeight: 20,
    loveYouRate: 12,
    whimRate: 12,
    rewardScale: 40,
    suggestionRate: 36,
  },
  capybara: {
    tone: "gentle",
    cadence: "occasional",
    pushiness: "never",
    dialogEffect: "whisper",
    whimId: "soak",
    titleLoves: ["rest", "soak", "sit"],
    habitWeight: 32,
    todoWeight: 78,
    nextActionsWeight: 26,
    loveYouRate: 18,
    whimRate: 10,
    rewardScale: 40,
    suggestionRate: 28,
  },
  piglet: {
    tone: "playful",
    cadence: "chatty",
    pushiness: "nudge",
    dialogEffect: "bounce",
    whimId: "nibble",
    titleLoves: ["eat", "cook", "snack"],
    habitWeight: 76,
    todoWeight: 34,
    nextActionsWeight: 24,
    loveYouRate: 20,
    whimRate: 14,
    rewardScale: 48,
    suggestionRate: 46,
  },
  "pack-00f0350b6374": {
    tone: "playful",
    cadence: "eager",
    pushiness: "nudge",
    dialogEffect: "sparkle",
    whimId: "walk",
    titleLoves: ["snow", "walk", "play", "rock"],
    habitWeight: 20,
    todoWeight: 72,
    nextActionsWeight: 38,
    loveYouRate: 16,
    whimRate: 14,
    rewardScale: 48,
    suggestionRate: 52,
  },
}

const NAME_SCENE_FITS: { test: RegExp; fit: Partial<FriendPersonality> }[] = [
  { test: /hyrax|marten|sable/, fit: NAMED_FRIEND_PERSONALITY_FITS["pack-00f0350b6374"]! },
  { test: /polecat|ferret/, fit: NAMED_FRIEND_PERSONALITY_FITS["tiny-cute-striped-polecat"]! },
  { test: /\bbat\b/, fit: NAMED_FRIEND_PERSONALITY_FITS.mouse! },
  { test: /turtle|tortoise/, fit: NAMED_FRIEND_PERSONALITY_FITS.skunk! },
]

export function personalityFitFor(animalId: string, displayName = ""): Partial<FriendPersonality> | undefined {
  const id = animalId.trim().toLowerCase()
  if (id && NAMED_FRIEND_PERSONALITY_FITS[id]) return NAMED_FRIEND_PERSONALITY_FITS[id]
  const slug = fitKey(animalId, displayName)
  if (slug && NAMED_FRIEND_PERSONALITY_FITS[slug]) return NAMED_FRIEND_PERSONALITY_FITS[slug]
  const hay = `${animalId} ${displayName}`.toLowerCase()
  for (const row of NAME_SCENE_FITS) {
    if (row.test.test(hay)) return row.fit
  }
  return undefined
}
