/**
 * lib/user-settings-store.ts — Cross-cutting user prefs
 *
 * Home location (city) used by Plan's day itinerary for sunrise/sunset lines.
 * Defaults to San Diego.
 *
 * `dayAnchorMinutes` is the time of day autogenerated completions fall back to
 * when a habit is ticked off for a day that is already over and there is no
 * painted Tracking time to read a real finish time from
 * (`lib/completion-window.ts`). Stored as minutes past midnight; 9:00 PM default.
 *
 * `birthday` is `YYYY-MM-DD` or empty. The Star Lord Report opens on that
 * month and day (the year is kept for the date field). February 29 is read
 * on March 1 in a common year.
 *
 * `pointsRules` is the global points catalog for rules that did not already
 * have a field (`lib/points-rules.ts`). A missing key means that rule's
 * default, so older installs stay on today's numbers until a row is edited.
 * Ritual points and the goal-focus multiplier stay their own fields and are
 * not copied into the map.
 *
 * Storage: localStorage today. Persist v5.
 */
"use client"

import { create } from "zustand"
import { persist } from "zustand/middleware"
import { createCogsJSONStorage } from "@/lib/persist-storage"
import { persistKey } from "@/lib/storage-keys"
import { clampAnchorMinutes, DEFAULT_DAY_ANCHOR_MINUTES } from "@/lib/completion-window"
import { clampFocusMultiplier, DEFAULT_GOAL_FOCUS_MULTIPLIER } from "@/lib/goal-focus"
import { parseBirthday } from "@/lib/star-lord"
import {
  clampPointAmount,
  DEFAULT_RITUAL_COMPLETION_BONUS,
  DEFAULT_RITUAL_SECTION_POINTS,
} from "@/lib/ritual-points"
import {
  clampPointsRule,
  isPointsRuleId,
  pointsRuleDef,
  sanitizePointsRules,
  type PointsRuleId,
} from "@/lib/points-rules"
import { bindUserPointsRules } from "@/lib/points-rules-live"

export const DEFAULT_HOME_CITY = "San Diego, California"

interface UserSettingsState {
  homeCity: string
  setHomeCity: (city: string) => void
  resetHomeLocation: () => void
  dayAnchorMinutes: number
  setDayAnchorMinutes: (minutes: number) => void
  /** Points per ritual section actually completed. Default 10. */
  ritualSectionPoints: number
  setRitualSectionPoints: (points: number) => void
  /** Bonus for submitting a ritual as done. Default 30. */
  ritualCompletionBonus: number
  setRitualCompletionBonus: (points: number) => void
  /** Multiplier for tasks serving tomorrow's focused goals. Default 1.5. */
  goalFocusMultiplier: number
  setGoalFocusMultiplier: (multiplier: number) => void
  /** `YYYY-MM-DD`, or empty when unset. Month and day open the birthday rite. */
  birthday: string
  setBirthday: (value: string) => void
  /**
   * Overrides for catalog rules that have no older field. Missing keys mean
   * the catalog default.
   */
  pointsRules: Partial<Record<PointsRuleId, number>>
  setPointsRule: (id: PointsRuleId, value: number) => void
  clearPointsRule: (id: PointsRuleId) => void
}

export const useUserSettingsStore = create<UserSettingsState>()(
  persist(
    (set) => ({
      homeCity: DEFAULT_HOME_CITY,
      setHomeCity: (city) => set({ homeCity: city.trim() || DEFAULT_HOME_CITY }),
      resetHomeLocation: () => set({ homeCity: DEFAULT_HOME_CITY }),
      dayAnchorMinutes: DEFAULT_DAY_ANCHOR_MINUTES,
      setDayAnchorMinutes: (minutes) => set({ dayAnchorMinutes: clampAnchorMinutes(minutes) }),
      ritualSectionPoints: DEFAULT_RITUAL_SECTION_POINTS,
      setRitualSectionPoints: (points) =>
        set({ ritualSectionPoints: clampPointAmount(points, DEFAULT_RITUAL_SECTION_POINTS) }),
      ritualCompletionBonus: DEFAULT_RITUAL_COMPLETION_BONUS,
      setRitualCompletionBonus: (points) =>
        set({ ritualCompletionBonus: clampPointAmount(points, DEFAULT_RITUAL_COMPLETION_BONUS) }),
      goalFocusMultiplier: DEFAULT_GOAL_FOCUS_MULTIPLIER,
      setGoalFocusMultiplier: (multiplier) => set({ goalFocusMultiplier: clampFocusMultiplier(multiplier) }),
      birthday: "",
      pointsRules: {},
      setPointsRule: (id, value) => {
        if (!isPointsRuleId(id) || pointsRuleDef(id).home !== "pointsRules") return
        const next = clampPointsRule(id, value)
        set((state) => {
          const pointsRules = { ...(state.pointsRules ?? {}) }
          if (next === pointsRuleDef(id).defaultValue) delete pointsRules[id]
          else pointsRules[id] = next
          return { pointsRules }
        })
      },
      clearPointsRule: (id) => {
        if (!isPointsRuleId(id)) return
        set((state) => {
          if (!state.pointsRules || state.pointsRules[id] === undefined) return state
          const pointsRules = { ...state.pointsRules }
          delete pointsRules[id]
          return { pointsRules }
        })
      },
      setBirthday: (value) => {
        const trimmed = value.trim()
        if (!trimmed) {
          set({ birthday: "" })
          return
        }
        const parsed = parseBirthday(trimmed)
        if (!parsed) return
        const month = String(parsed.month).padStart(2, "0")
        const day = String(parsed.day).padStart(2, "0")
        const year = parsed.year ? String(parsed.year).padStart(4, "0") : ""
        set({ birthday: year ? `${year}-${month}-${day}` : `${month}-${day}` })
      },
    }),
    {
      name: persistKey("user-settings"),
      version: 5,
      storage: createCogsJSONStorage(),
      migrate: (state, version) => {
        const prev = (state ?? {}) as Partial<UserSettingsState>
        const withAnchor =
          version < 2 ? { ...prev, dayAnchorMinutes: DEFAULT_DAY_ANCHOR_MINUTES } : prev
        const withPoints =
          version < 3
            ? {
                ...withAnchor,
                ritualSectionPoints: DEFAULT_RITUAL_SECTION_POINTS,
                ritualCompletionBonus: DEFAULT_RITUAL_COMPLETION_BONUS,
                goalFocusMultiplier: DEFAULT_GOAL_FOCUS_MULTIPLIER,
              }
            : withAnchor
        const withBirthday = version < 4 ? { ...withPoints, birthday: "" } : withPoints
        if (version < 5) {
          return { ...withBirthday, pointsRules: {} } as UserSettingsState
        }
        return {
          ...withBirthday,
          pointsRules: sanitizePointsRules((withBirthday as UserSettingsState).pointsRules),
        } as UserSettingsState
      },
    },
  ),
)

bindUserPointsRules({
  get: () => useUserSettingsStore.getState(),
  setMap: (id, value) => useUserSettingsStore.getState().setPointsRule(id, value),
  clearMap: (id) => useUserSettingsStore.getState().clearPointsRule(id),
  setRitualSectionPoints: (value) => useUserSettingsStore.getState().setRitualSectionPoints(value),
  setRitualCompletionBonus: (value) => useUserSettingsStore.getState().setRitualCompletionBonus(value),
  setGoalFocusMultiplier: (value) => useUserSettingsStore.getState().setGoalFocusMultiplier(value),
})
