/**
 * lib/user-settings-store.ts — Cross-cutting user prefs
 *
 * Home location (city) used by Plan's day itinerary for sunrise/sunset lines.
 * Defaults to San Diego.
 *
 * `dayAnchorMinutes` is the time of day autogenerated completions fall back to
 * when a habit is ticked off for a day that is already over and there is no
 * painted Tracking time to read a real finish time from
 * (`lib/completion-window.ts`). Stored as minutes past midnight; 9:00 PM default.
 *
 * Storage: localStorage today.
 */
"use client"

import { create } from "zustand"
import { persist } from "zustand/middleware"
import { createCogsJSONStorage } from "@/lib/persist-storage"
import { persistKey } from "@/lib/storage-keys"
import { clampAnchorMinutes, DEFAULT_DAY_ANCHOR_MINUTES } from "@/lib/completion-window"

export const DEFAULT_HOME_CITY = "San Diego, California"

interface UserSettingsState {
  homeCity: string
  setHomeCity: (city: string) => void
  resetHomeLocation: () => void
  dayAnchorMinutes: number
  setDayAnchorMinutes: (minutes: number) => void
}

export const useUserSettingsStore = create<UserSettingsState>()(
  persist(
    (set) => ({
      homeCity: DEFAULT_HOME_CITY,
      setHomeCity: (city) => set({ homeCity: city.trim() || DEFAULT_HOME_CITY }),
      resetHomeLocation: () => set({ homeCity: DEFAULT_HOME_CITY }),
      dayAnchorMinutes: DEFAULT_DAY_ANCHOR_MINUTES,
      setDayAnchorMinutes: (minutes) => set({ dayAnchorMinutes: clampAnchorMinutes(minutes) }),
    }),
    {
      name: persistKey("user-settings"),
      version: 2,
      storage: createCogsJSONStorage(),
      migrate: (state, version) => {
        const prev = (state ?? {}) as Partial<UserSettingsState>
        if (version < 2) return { ...prev, dayAnchorMinutes: DEFAULT_DAY_ANCHOR_MINUTES } as UserSettingsState
        return prev as UserSettingsState
      },
    },
  ),
)
