import { mkdirSync, mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import path from "node:path"
import { afterEach, describe, expect, it } from "vitest"
import { archiveShot, localArchiveStamp, readFeatureNotes, safeRepoFile, saveFeatureNotes, seedFeatureNotes, writeReelIndex } from "@/scripts/screenshot-archive.mjs"
import { createReelServer } from "@/scripts/screenshot-reel-server.mjs"

const dirs: string[] = []

afterEach(() => {
  for (const dir of dirs.splice(0)) rmSync(dir, { recursive: true, force: true })
})

function tempDir() {
  const dir = mkdtempSync(path.join(tmpdir(), "screenshot-reel-"))
  dirs.push(dir)
  return dir
}

function readReel(dir: string) {
  const text = readFileSync(path.join(dir, "reel.js"), "utf8")
  expect(text.startsWith("/* Generated by scripts/screenshot-archive.mjs")).toBe(true)
  expect(text).toContain("window.SCREENSHOT_REEL = ")
  expect(text.trimEnd().endsWith(";")).toBe(true)
  expect(text).not.toMatch(/\bexport\b/)
  const json = text.slice(text.indexOf("window.SCREENSHOT_REEL = ") + "window.SCREENSHOT_REEL = ".length).trim().replace(/;$/, "")
  return JSON.parse(json) as {
    generatedAt: string
    shots: { file: string; view: string; area: string; frames: { src: string; label: string; kind: string }[] }[]
    groups: { area: string; files: string[] }[]
  }
}

describe("archiveShot", () => {
  it("copies the live PNG into a timestamped history file and keeps the source", () => {
    const dir = tempDir()
    const src = path.join(dir, "10-operations.png")
    writeFileSync(src, "png-bytes")
    const when = new Date("2026-09-20T21:30:00.000Z")

    const dest = archiveShot(dir, "10-operations.png", when)

    expect(localArchiveStamp(when)).toBe("2026-09-20T14-30-00")
    expect(dest).toBe(path.join(dir, "history", "10-operations", "2026-09-20T14-30-00.png"))
    expect(readFileSync(dest!, "utf8")).toBe("png-bytes")
    expect(readFileSync(src, "utf8")).toBe("png-bytes")
    expect(statSync(src).isFile()).toBe(true)
  })

  it("adds a numeric suffix when that archive name already exists", () => {
    const dir = tempDir()
    writeFileSync(path.join(dir, "10-operations.png"), "live")
    const when = new Date("2026-09-20T21:30:00.000Z")

    const first = archiveShot(dir, "10-operations.png", when)
    writeFileSync(path.join(dir, "10-operations.png"), "live-again")
    const second = archiveShot(dir, "10-operations.png", when)

    expect(path.basename(first!)).toBe("2026-09-20T14-30-00.png")
    expect(path.basename(second!)).toBe("2026-09-20T14-30-00-2.png")
    expect(readFileSync(first!, "utf8")).toBe("live")
    expect(readFileSync(second!, "utf8")).toBe("live-again")
    expect(readFileSync(path.join(dir, "10-operations.png"), "utf8")).toBe("live-again")
  })

  it("skips a missing source and does not create history", () => {
    const dir = tempDir()
    expect(archiveShot(dir, "missing.png")).toBeNull()
    expect(archiveShot(dir, "../10-operations.png")).toBeNull()
    expect(statSync(dir).isDirectory()).toBe(true)
  })
})

describe("writeReelIndex", () => {
  it("orders history oldest to newest and keeps the live PNG last", () => {
    const dir = tempDir()
    writeFileSync(path.join(dir, "10-operations.png"), "current")
    writeFileSync(
      path.join(dir, "10-operations.txt"),
      "SCREENSHOT: 10-operations.png\nVIEW: From sidecar\nAREA: Sidecar area\n",
    )
    writeFileSync(
      path.join(dir, "README.md"),
      "| File | Date | Status | View |\n| `10-operations.png` | 2026-09-20 | unknown | From table |\n| `12-docs*.png` | — | missing | Docs tab |\n",
    )
    const history = path.join(dir, "history", "10-operations")
    mkdirSync(history, { recursive: true })
    writeFileSync(path.join(history, "2026-09-21T09-00-00.png"), "newer")
    writeFileSync(path.join(history, "2026-09-20T14-30-00.png"), "older")
    writeFileSync(path.join(history, "2026-09-20T14-30-00-2.png"), "older-2")

    const written = writeReelIndex(dir)
    const reel = readReel(dir)
    const shot = reel.shots.find((item) => item.file === "10-operations.png")

    expect(written.shotCount).toBe(1)
    expect(written.frameCount).toBe(4)
    expect(shot).toMatchObject({ view: "From sidecar", area: "Sidecar area" })
    expect(shot?.frames.map((frame) => frame.src)).toEqual([
      "history/10-operations/2026-09-20T14-30-00.png",
      "history/10-operations/2026-09-20T14-30-00-2.png",
      "history/10-operations/2026-09-21T09-00-00.png",
      "10-operations.png",
    ])
    expect(shot?.frames.map((frame) => frame.kind)).toEqual(["history", "history", "history", "current"])
    expect(shot?.frames[0].label).toBe("2026-09-20 14:30:00")
    expect(shot?.frames[1].label).toBe("2026-09-20 14:30:00 (2)")
    expect(shot?.frames.at(-1)?.kind).toBe("current")
    expect(reel.groups).toEqual([{ area: "Operations", files: ["10-operations.png"] }])
    expect(readFileSync(path.join(dir, "10-operations.png"), "utf8")).toBe("current")
  })

  it("shows a current-only PNG and a history-only basename", () => {
    const dir = tempDir()
    writeFileSync(path.join(dir, "01-home-daily-habits.png"), "now")
    writeFileSync(
      path.join(dir, "README.md"),
      "| `01-home-daily-habits.png` | 2026-09-23 | unknown | Home → Habits → Daily |\n| `habits-noble-gas-rail.png` | 2026-09-20 | unknown | Habits control-panel crop; no sidecar |\n",
    )
    writeFileSync(path.join(dir, "habits-noble-gas-rail.png"), "crop")
    const onlyHistory = path.join(dir, "history", "07-analytics")
    mkdirSync(onlyHistory, { recursive: true })
    writeFileSync(path.join(onlyHistory, "2026-01-01T00-00-00.png"), "old")

    writeReelIndex(dir)
    const reel = readReel(dir)

    const habits = reel.shots.find((shot) => shot.file === "01-home-daily-habits.png")
    expect(habits?.frames).toHaveLength(1)
    expect(habits?.frames[0]).toMatchObject({ src: "01-home-daily-habits.png", kind: "current" })
    expect(habits?.view).toBe("Home → Habits → Daily")
    expect(habits?.area).toBe("Home → Habits")

    const analytics = reel.shots.find((shot) => shot.file === "07-analytics.png")
    expect(analytics?.frames).toEqual([
      { src: "history/07-analytics/2026-01-01T00-00-00.png", label: "2026-01-01 00:00:00", kind: "history" },
    ])

    const crop = reel.shots.find((shot) => shot.file === "habits-noble-gas-rail.png")
    expect(crop?.view).toBe("Habits control-panel crop; no sidecar")
    expect(crop?.area).toBe("Other")

    expect(reel.groups.map((group) => group.area)).toEqual(["Home → Habits", "Analytics", "Other"])
    expect(reel.groups[0].files).toEqual(["01-home-daily-habits.png"])
  })
})

describe("feature notes", () => {
  function repoWithOps() {
    const repo = tempDir()
    const shots = path.join(repo, "docs", "screenshots")
    mkdirSync(path.join(repo, "components", "Operations"), { recursive: true })
    mkdirSync(path.join(repo, "docs"), { recursive: true })
    mkdirSync(shots, { recursive: true })
    writeFileSync(path.join(repo, "components", "Operations", "README.md"), "# Ops\n")
    writeFileSync(path.join(repo, "docs", "PLAN_OF_ACTION.md"), "# Plan\n")
    writeFileSync(path.join(shots, "10-operations-workspace.png"), "png")
    writeFileSync(
      path.join(shots, "10-operations-workspace.txt"),
      [
        "SCREENSHOT: 10-operations-workspace.png",
        "VIEW: From sidecar",
        "AREA: Operations workspace",
        "SOURCE FILES:",
        "  - components/Operations/OperationWorkspace.tsx",
        "================================================================================",
        "VIEW-SPECIFIC",
        "The workspace paragraph.",
        "",
      ].join("\n"),
    )
    return { repo, shots }
  }

  it("fills absent fields and keeps saved ones", () => {
    const { repo, shots } = repoWithOps()
    writeFileSync(
      path.join(shots, "feature-notes.json"),
      JSON.stringify({ "10-operations-workspace.png": { name: "Kept name", docPath: "" } }, null, 2),
    )

    seedFeatureNotes(shots, repo)
    const notes = readFeatureNotes(shots)
    expect(notes["10-operations-workspace.png"]).toEqual({
      name: "Kept name",
      description: "The workspace paragraph.",
      styleNotes: "",
      docPath: "",
    })

    seedFeatureNotes(shots, repo)
    expect(readFeatureNotes(shots)["10-operations-workspace.png"].name).toBe("Kept name")
  })

  it("maps the first source folder README, else a docs page", () => {
    const { repo, shots } = repoWithOps()
    seedFeatureNotes(shots, repo)
    expect(readFeatureNotes(shots)["10-operations-workspace.png"]).toMatchObject({
      name: "From sidecar",
      description: "The workspace paragraph.",
      styleNotes: "",
      docPath: "components/Operations/README.md",
    })

    writeFileSync(path.join(shots, "06-scheduler.png"), "png")
    writeFileSync(
      path.join(shots, "06-scheduler.txt"),
      "VIEW: Scheduler\nSOURCE FILES:\n  - lib/missing.ts\n\nSee docs/PLAN_OF_ACTION.md for the plan.\n",
    )
    seedFeatureNotes(shots, repo)
    expect(readFeatureNotes(shots)["06-scheduler.png"].docPath).toBe("docs/PLAN_OF_ACTION.md")
  })

  it("rejects markdown paths that leave the repo", () => {
    const { repo, shots } = repoWithOps()
    expect(safeRepoFile(repo, "../secret.md", { ext: ".md" })).toBeNull()
    expect(safeRepoFile(repo, "components/Operations/README.js", { ext: ".md" })).toBeNull()
    expect(() =>
      saveFeatureNotes(shots, repo, {
        file: "10-operations-workspace.png",
        record: { name: "N", description: "", styleNotes: "", docPath: "../secret.md" },
      }),
    ).toThrow(/doc path rejected/)

    saveFeatureNotes(shots, repo, {
      file: "10-operations-workspace.png",
      record: { name: "N", description: "D", styleNotes: "quiet", docPath: "components/Operations/README.md" },
    })
    saveFeatureNotes(shots, repo, {
      notes: {
        "10-operations-workspace.png": {
          name: "Whole",
          description: "D",
          styleNotes: "quiet",
          docPath: "components/Operations/README.md",
        },
      },
    })
    const text = readFileSync(path.join(shots, "feature-notes.json"), "utf8")
    expect(text.endsWith("\n")).toBe(true)
    expect(JSON.parse(text)["10-operations-workspace.png"]).toEqual({
      name: "Whole",
      description: "D",
      styleNotes: "quiet",
      docPath: "components/Operations/README.md",
    })
  })

  it("serves a doc and saves one record", async () => {
    const { repo, shots } = repoWithOps()
    seedFeatureNotes(shots, repo)
    const server = createReelServer(repo, shots)
    await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", () => resolve()))
    const port = (server.address() as { port: number }).port
    try {
      const rejected = await fetch(`http://127.0.0.1:${port}/api/doc?path=${encodeURIComponent("../secret.md")}`)
      expect(rejected.status).toBe(400)
      const doc = await fetch(
        `http://127.0.0.1:${port}/api/doc?path=${encodeURIComponent("components/Operations/README.md")}`,
      )
      expect(await doc.text()).toBe("# Ops\n")
      const saved = await fetch(`http://127.0.0.1:${port}/api/notes`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          file: "10-operations-workspace.png",
          record: { name: "From sidecar", description: "The workspace paragraph.", styleNotes: "brass", docPath: "components/Operations/README.md" },
        }),
      })
      expect(saved.status).toBe(200)
      const notes = await fetch(`http://127.0.0.1:${port}/api/notes`)
      expect((await notes.json())["10-operations-workspace.png"].styleNotes).toBe("brass")
      const escaped = await fetch(`http://127.0.0.1:${port}/api/doc?path=${encodeURIComponent("components/Operations/../../../etc/passwd.md")}`)
      expect(escaped.status).toBe(400)
    } finally {
      await new Promise<void>((resolve, reject) => server.close((error) => (error ? reject(error) : resolve())))
    }
  })
})
