/**
 * Screenshot evolution archive.
 *
 * Capture calls `archiveShot(outDir, filename)` before it overwrites a live PNG.
 * The previous file is copied (never renamed or deleted) to:
 *
 *   <outDir>/history/<basename-without-.png>/<YYYY-MM-DDTHH-mm-ss>.png
 *
 * Local time. Colons in the clock are hyphens. If that name already exists,
 * the next free `-2`, `-3`, … suffix is used.
 *
 * `writeReelIndex(outDir)` scans live `*.png` files and `history/<basename>/*.png`,
 * writes `<outDir>/reel.js`, and fills any missing fields in `feature-notes.json`.
 * History frames of one basename share that one record.
 */
import {
  closeSync,
  constants,
  copyFileSync,
  existsSync,
  mkdirSync,
  openSync,
  readdirSync,
  readFileSync,
  readSync,
  realpathSync,
  statSync,
  writeFileSync,
} from "node:fs"
import path from "node:path"

/** Feature names for the numeric prefixes in docs/screenshots. */
const PREFIX_AREAS = {
  "01": "Home → Habits",
  "02": "Home → Plan",
  "03": "Home → To Do",
  "04": "Home → Goals",
  "05": "Lists",
  "06": "Scheduler",
  "07": "Analytics",
  "08": "Home → Tracking",
  "09": "Modules",
  "10": "Operations",
  "12": "Docs",
  "20": "Dialogs",
  "21": "Item detail",
}

const STATUS_ROW =
  /^\|\s*`([^`*]+\.png)`\s*\|\s*[^|]*\|\s*[^|]*\|\s*([^|]+)\|\s*$/

/**
 * @param {Date} date
 * @returns {string} `YYYY-MM-DDTHH-mm-ss` in local time
 */
export function localArchiveStamp(date) {
  const pad = (n) => String(n).padStart(2, "0")
  return (
    `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}` +
    `T${pad(date.getHours())}-${pad(date.getMinutes())}-${pad(date.getSeconds())}`
  )
}

/**
 * Copy a live screenshot into history before capture overwrites it.
 *
 * @param {string} outDir docs/screenshots directory
 * @param {string} filename live PNG name, e.g. `10-operations.png`
 * @param {Date} [when] clock for the archive name; defaults to now
 * @returns {string|null} destination path, or null when the live file is absent
 */
export function archiveShot(outDir, filename, when = new Date()) {
  if (typeof filename !== "string" || filename !== path.basename(filename)) return null
  if (!/\.png$/i.test(filename)) return null
  const src = path.join(outDir, filename)
  if (!existsSync(src) || !statSync(src).isFile()) return null

  const clock = when instanceof Date ? when : new Date(when)
  if (Number.isNaN(clock.getTime())) {
    throw new Error("archiveShot: invalid timestamp")
  }

  const basename = filename.replace(/\.png$/i, "")
  const historyDir = path.join(outDir, "history", basename)
  mkdirSync(historyDir, { recursive: true })

  const stamp = localArchiveStamp(clock)
  for (let n = 1; n <= 1000; n += 1) {
    const name = n === 1 ? `${stamp}.png` : `${stamp}-${n}.png`
    const dest = path.join(historyDir, name)
    try {
      copyFileSync(src, dest, constants.COPYFILE_EXCL)
      return dest
    } catch (err) {
      if (err && err.code === "EEXIST") continue
      throw err
    }
  }
  throw new Error(`archiveShot: no free name for ${stamp}`)
}

/**
 * Scan live PNGs and history frames, then write `reel.js`.
 *
 * @param {string} outDir docs/screenshots directory
 * @returns {{ path: string, shotCount: number, frameCount: number }}
 */
export function writeReelIndex(outDir) {
  if (!existsSync(outDir) || !statSync(outDir).isDirectory()) {
    throw new Error(`screenshot dir missing: ${outDir}`)
  }

  const reel = buildReel(outDir)
  const dest = path.join(outDir, "reel.js")
  const body =
    "/* Generated by scripts/screenshot-archive.mjs — npm run screenshot-reel */\n" +
    `window.SCREENSHOT_REEL = ${JSON.stringify(reel, null, 2)};\n`
  writeFileSync(dest, body)
  seedFeatureNotes(outDir)
  const frameCount = reel.shots.reduce((sum, shot) => sum + shot.frames.length, 0)
  return { path: dest, shotCount: reel.shots.length, frameCount }
}

/**
 * @param {string} outDir
 */
function buildReel(outDir) {
  const views = parseStatusViews(readOptional(path.join(outDir, "README.md")))
  const byBase = new Map()

  for (const name of readdirSync(outDir)) {
    if (!/\.png$/i.test(name)) continue
    const abs = path.join(outDir, name)
    if (!statSync(abs).isFile()) continue
    const shot = ensureShot(byBase, name)
    shot.current = {
      src: name,
      label: formatLocal(statSync(abs).mtime),
      kind: "current",
    }
  }

  const historyRoot = path.join(outDir, "history")
  if (existsSync(historyRoot) && statSync(historyRoot).isDirectory()) {
    for (const base of readdirSync(historyRoot)) {
      const dir = path.join(historyRoot, base)
      if (!statSync(dir).isDirectory()) continue
      const file = `${base}.png`
      const shot = ensureShot(byBase, file)
      for (const name of readdirSync(dir)) {
        if (!/\.png$/i.test(name)) continue
        const abs = path.join(dir, name)
        if (!statSync(abs).isFile()) continue
        const parsed = parseHistoryName(name)
        shot.history.push({
          src: `history/${base}/${name}`,
          label: parsed.label,
          kind: "history",
          sortKey: parsed.sortKey,
          sortN: parsed.sortN,
        })
      }
    }
  }

  const shots = [...byBase.values()]
    .map((shot) => finalizeShot(outDir, shot, views))
    .filter((shot) => shot.frames.length > 0)
    .sort((a, b) => a.file.localeCompare(b.file))

  return {
    generatedAt: new Date().toISOString(),
    shots,
    groups: buildGroups(shots),
  }
}

function ensureShot(byBase, file) {
  let shot = byBase.get(file)
  if (!shot) {
    shot = { file, current: null, history: [] }
    byBase.set(file, shot)
  }
  return shot
}

function finalizeShot(outDir, shot, views) {
  const sidecar = parseSidecar(readHead(path.join(outDir, shot.file.replace(/\.png$/i, ".txt"))))
  const prefix = prefixArea(shot.file)
  const tableView = views.get(shot.file) || ""
  const view = sidecar.VIEW || tableView || shot.file.replace(/\.png$/i, "")
  const area = sidecar.AREA || prefix || "Other"

  const history = [...shot.history].sort((a, b) => {
    if (a.sortKey < b.sortKey) return -1
    if (a.sortKey > b.sortKey) return 1
    return a.sortN - b.sortN
  })

  const frames = history.map(({ src, label, kind }) => ({ src, label, kind }))
  if (shot.current) frames.push(shot.current)

  return { file: shot.file, view, area, frames }
}

function buildGroups(shots) {
  const groups = new Map()
  for (const shot of shots) {
    const area = prefixArea(shot.file) || shot.area || "Other"
    if (!groups.has(area)) groups.set(area, [])
    groups.get(area).push(shot.file)
  }
  return [...groups.entries()]
    .map(([area, files]) => ({
      area,
      files: files.sort((a, b) => a.localeCompare(b)),
    }))
    .sort((a, b) => {
      const rank = (group) => {
        const prefix = group.files
          .map((file) => /^(\d+)/.exec(file)?.[1])
          .filter(Boolean)
          .map(Number)
          .sort((x, y) => x - y)[0]
        return prefix ?? 9999
      }
      const delta = rank(a) - rank(b)
      if (delta !== 0) return delta
      return a.area.localeCompare(b.area)
    })
}

function prefixArea(file) {
  const prefix = /^(\d{2})-/.exec(file)?.[1]
  return prefix ? PREFIX_AREAS[prefix] || "" : ""
}

function parseStatusViews(markdown) {
  const views = new Map()
  if (!markdown) return views
  for (const line of markdown.split("\n")) {
    const match = STATUS_ROW.exec(line)
    if (!match) continue
    views.set(match[1], match[2].trim())
  }
  return views
}

function parseSidecar(text) {
  const meta = {}
  if (!text) return meta
  const lines = text.split("\n").slice(0, 12)
  for (const line of lines) {
    const match = /^(SCREENSHOT|VIEW|AREA):\s*(.*)$/.exec(line)
    if (!match) continue
    const value = match[2].trim()
    if (value) meta[match[1]] = value
  }
  return meta
}

function parseHistoryName(name) {
  const match = /^(\d{4}-\d{2}-\d{2}T\d{2}-\d{2}-\d{2})(?:-(\d+))?\.png$/i.exec(name)
  if (!match) {
    return { label: name.replace(/\.png$/i, ""), sortKey: name, sortN: 0 }
  }
  const stamp = match[1]
  const suffix = match[2] ? Number(match[2]) : 1
  const [day, clock] = stamp.split("T")
  const labelTime = clock.replace(/-/g, ":")
  const extra = match[2] ? ` (${match[2]})` : ""
  return {
    label: `${day} ${labelTime}${extra}`,
    sortKey: stamp,
    sortN: suffix,
  }
}

function formatLocal(date) {
  const pad = (n) => String(n).padStart(2, "0")
  return (
    `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())} ` +
    `${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}`
  )
}

function readOptional(file) {
  if (!existsSync(file)) return ""
  return readFileSync(file, "utf8")
}

function readHead(file) {
  if (!existsSync(file)) return ""
  const fd = openSync(file, "r")
  try {
    const buf = Buffer.alloc(4096)
    const n = readSync(fd, buf, 0, buf.length, 0)
    return buf.subarray(0, n).toString("utf8")
  } finally {
    closeSync(fd)
  }
}

const FEATURE_NOTES = "feature-notes.json"
const NOTE_FIELDS = ["name", "description", "styleNotes", "docPath"]
const IMAGE_EXTS = [".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg"]

/**
 * Keep a markdown path inside the repo. Empty or escaping paths return null.
 * `ext` / `exts` limit the filename suffix (lowercase, including the dot).
 *
 * @param {string} repoRoot
 * @param {string} rel
 * @param {{ ext?: string, exts?: string[] }} [options]
 * @returns {{ abs: string, rel: string } | null}
 */
export function safeRepoFile(repoRoot, rel, options = {}) {
  if (typeof rel !== "string") return null
  const trimmed = rel.trim().replace(/\\/g, "/")
  if (!trimmed || trimmed.includes("\0")) return null
  if (trimmed.startsWith("/") || /^[A-Za-z]:/.test(trimmed)) return null
  const ext = path.posix.extname(trimmed).toLowerCase()
  if (options.ext && ext !== options.ext.toLowerCase()) return null
  if (options.exts && !options.exts.map((item) => item.toLowerCase()).includes(ext)) return null

  const root = path.resolve(repoRoot)
  const abs = path.resolve(root, trimmed)
  const relBack = path.relative(root, abs)
  if (!relBack || relBack.startsWith("..") || path.isAbsolute(relBack)) return null

  let realAbs = abs
  if (existsSync(abs)) {
    const realRoot = realpathSync(root)
    realAbs = realpathSync(abs)
    const realRel = path.relative(realRoot, realAbs)
    if (realRel.startsWith("..") || path.isAbsolute(realRel)) return null
  }
  return { abs: realAbs, rel: relBack.split(path.sep).join("/") }
}

/**
 * Resolve a markdown image path against the document that cited it.
 * @param {string} repoRoot
 * @param {string} docPath
 * @param {string} src
 */
export function resolveRepoAsset(repoRoot, docPath, src) {
  if (typeof src !== "string") return null
  const raw = src.trim().replace(/\\/g, "/")
  if (!raw || /^[a-z][a-z0-9+.-]*:/i.test(raw)) return null
  const doc = safeRepoFile(repoRoot, docPath, { ext: ".md" })
  if (!doc) return null
  const joined = path.posix.normalize(path.posix.join(path.posix.dirname(doc.rel), raw))
  return safeRepoFile(repoRoot, joined, { exts: IMAGE_EXTS })
}

/**
 * Fill absent feature-note fields. Saved name, description, style notes, and
 * doc path are left alone. One record per screenshot basename.
 *
 * @param {string} outDir
 * @param {string} [repoRoot]
 */
export function seedFeatureNotes(outDir, repoRoot = path.resolve(outDir, "..", "..")) {
  const views = parseStatusViews(readOptional(path.join(outDir, "README.md")))
  const notes = readFeatureNotes(outDir)
  for (const file of listShotFiles(outDir)) {
    const prior = notes[file]
    const base = prior && typeof prior === "object" && !Array.isArray(prior) ? prior : {}
    const proposal = proposeFeature(outDir, repoRoot, file, views)
    const next = {}
    for (const key of NOTE_FIELDS) {
      next[key] = Object.prototype.hasOwnProperty.call(base, key) ? asText(base[key]) : proposal[key]
    }
    notes[file] = next
  }
  writeFeatureNotes(outDir, notes)
  return { path: path.join(outDir, FEATURE_NOTES), count: Object.keys(notes).length }
}

/**
 * @param {string} outDir
 */
export function readFeatureNotes(outDir) {
  const file = path.join(outDir, FEATURE_NOTES)
  if (!existsSync(file)) return {}
  const text = readFileSync(file, "utf8").trim()
  if (!text) return {}
  const parsed = JSON.parse(text)
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error("feature-notes.json is not an object")
  }
  return parsed
}

/**
 * Save one record (`{ file, record }`) or the whole map (`{ notes }` or a
 * basename → record object). Only `feature-notes.json` is written.
 *
 * @param {string} outDir
 * @param {string} repoRoot
 * @param {object} body
 */
export function saveFeatureNotes(outDir, repoRoot, body) {
  if (!body || typeof body !== "object" || Array.isArray(body)) {
    throw new Error("bad notes")
  }
  const current = readFeatureNotes(outDir)
  let next
  if (typeof body.file === "string" && body.record && typeof body.record === "object" && !Array.isArray(body.record)) {
    const file = shotKey(body.file)
    next = { ...current, [file]: normalizeRecord(body.record, repoRoot) }
  } else if (body.notes && typeof body.notes === "object" && !Array.isArray(body.notes)) {
    next = normalizeMap(body.notes, repoRoot)
  } else if (Object.keys(body).some((key) => key.toLowerCase().endsWith(".png"))) {
    next = normalizeMap(body, repoRoot)
  } else {
    throw new Error("bad notes")
  }
  writeFeatureNotes(outDir, next)
  return next
}

function writeFeatureNotes(outDir, notes) {
  const ordered = {}
  for (const file of Object.keys(notes).sort()) {
    const rec = notes[file]
    ordered[file] = {
      name: asText(rec.name),
      description: asText(rec.description),
      styleNotes: asText(rec.styleNotes),
      docPath: asText(rec.docPath),
    }
  }
  writeFileSync(path.join(outDir, FEATURE_NOTES), `${JSON.stringify(ordered, null, 2)}\n`)
}

function normalizeMap(map, repoRoot) {
  const next = {}
  for (const [file, record] of Object.entries(map)) {
    next[shotKey(file)] = normalizeRecord(record, repoRoot)
  }
  return next
}

function normalizeRecord(record, repoRoot) {
  if (!record || typeof record !== "object" || Array.isArray(record)) {
    throw new Error("bad record")
  }
  const docPath = asText(record.docPath).trim()
  let stored = ""
  if (docPath) {
    const safe = safeRepoFile(repoRoot, docPath, { ext: ".md" })
    if (!safe) throw new Error("doc path rejected")
    stored = safe.rel
  }
  return {
    name: asText(record.name),
    description: asText(record.description),
    styleNotes: asText(record.styleNotes),
    docPath: stored,
  }
}

function shotKey(file) {
  if (typeof file !== "string" || file !== path.basename(file) || !/\.png$/i.test(file)) {
    throw new Error("bad shot")
  }
  return file
}

function asText(value) {
  if (value == null) return ""
  return String(value)
}

function listShotFiles(outDir) {
  const files = new Set()
  if (!existsSync(outDir)) return []
  for (const name of readdirSync(outDir)) {
    if (!/\.png$/i.test(name)) continue
    if (statSync(path.join(outDir, name)).isFile()) files.add(name)
  }
  const historyRoot = path.join(outDir, "history")
  if (existsSync(historyRoot) && statSync(historyRoot).isDirectory()) {
    for (const base of readdirSync(historyRoot)) {
      const dir = path.join(historyRoot, base)
      if (!statSync(dir).isDirectory()) continue
      const hasPng = readdirSync(dir).some((name) => /\.png$/i.test(name) && statSync(path.join(dir, name)).isFile())
      if (hasPng) files.add(`${base}.png`)
    }
  }
  return [...files].sort()
}

function proposeFeature(outDir, repoRoot, file, views) {
  const text = readOptional(path.join(outDir, file.replace(/\.png$/i, ".txt")))
  const meta = parseSidecarDocument(text)
  const name = meta.VIEW || meta.AREA || views.get(file) || file.replace(/\.png$/i, "")
  return {
    name,
    description: meta.viewSpecific,
    styleNotes: "",
    docPath: docPathForSources(meta.sources, text, repoRoot),
  }
}

function docPathForSources(sources, text, repoRoot) {
  for (const source of sources) {
    const mapped = readmeForSource(repoRoot, source)
    if (mapped) return mapped
  }
  return docsPageInText(text, repoRoot)
}

function readmeForSource(repoRoot, source) {
  const rel = source.trim().replace(/^`+|`+$/g, "").replace(/\\/g, "/")
  if (!rel) return ""
  if (/\.md$/i.test(rel)) {
    const asDoc = safeRepoFile(repoRoot, rel, { ext: ".md" })
    if (asDoc && existsSync(asDoc.abs)) return asDoc.rel
  }
  const dir = path.posix.dirname(rel)
  const readme = !dir || dir === "." ? "README.md" : `${dir}/README.md`
  const safe = safeRepoFile(repoRoot, readme, { ext: ".md" })
  if (safe && existsSync(safe.abs)) return safe.rel
  return ""
}

function docsPageInText(text, repoRoot) {
  if (!text) return ""
  const re = /(?:^|[\s`"'(])([A-Za-z0-9_./-]+\.md)\b/g
  let match
  while ((match = re.exec(text))) {
    const token = match[1]
    const candidates = token.includes("/") ? [token] : [`docs/${token}`, token]
    for (const candidate of candidates) {
      const safe = safeRepoFile(repoRoot, candidate, { ext: ".md" })
      if (safe && existsSync(safe.abs)) return safe.rel
    }
  }
  return ""
}

function parseSidecarDocument(text) {
  const meta = { VIEW: "", AREA: "", sources: [], viewSpecific: "" }
  if (!text) return meta
  let inSources = false
  let inSpecific = false
  const specific = []
  for (const line of text.split("\n")) {
    if (!inSpecific) {
      const field = /^(SCREENSHOT|VIEW|AREA):\s*(.*)$/.exec(line)
      if (field) {
        inSources = false
        if (field[2].trim()) meta[field[1]] = field[2].trim()
        continue
      }
      if (/^SOURCE FILES:\s*$/.test(line)) {
        inSources = true
        continue
      }
      if (inSources) {
        const item = /^\s*-\s+(.+?)\s*$/.exec(line)
        if (item) {
          meta.sources.push(item[1].trim())
          continue
        }
        if (!line.trim() || line.startsWith("=")) inSources = false
      }
    }
    if (/^VIEW-SPECIFIC\s*$/.test(line)) {
      inSpecific = true
      inSources = false
      continue
    }
    if (inSpecific) specific.push(line)
  }
  meta.viewSpecific = specific.join("\n").trim()
  return meta
}
